[alias]
lint = "clippy --all-targets --all-features"
lint_fix = "clippy --fix --all-targets --all-features --allow-dirty --allow-staged"
tidy = "fmt --all -- --config style_edition=2027,wrap_comments=true,comment_width=100,imports_granularity=Item,group_imports=One,normalize_comments=true"
tidy_check = "fmt --all -- --check --config style_edition=2027,wrap_comments=true,comment_width=100,imports_granularity=Item,group_imports=One,normalize_comments=true"
